// src/ai/flows/refine-prompt.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow for refining a basic prompt idea into a more effective and detailed prompt.
 *
 * - refinePrompt - A function that takes a basic prompt idea and refines it using AI.
 * - RefinePromptInput - The input type for the refinePrompt function.
 * - RefinePromptOutput - The output type for the refinePrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefinePromptInputSchema = z.object({
  promptIdea: z.string().describe('The basic prompt idea to be refined.'),
  style: z.string().optional().describe('The desired style of the prompt.'),
  length: z.string().optional().describe('The desired length of the prompt.'),
  tone: z.string().optional().describe('The desired tone of the prompt.'),
});
export type RefinePromptInput = z.infer<typeof RefinePromptInputSchema>;

const RefinePromptOutputSchema = z.object({
  refinedPrompt: z.string().describe('The refined prompt generated by the AI.'),
});
export type RefinePromptOutput = z.infer<typeof RefinePromptOutputSchema>;

export async function refinePrompt(input: RefinePromptInput): Promise<RefinePromptOutput> {
  return refinePromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'refinePromptPrompt',
  input: {schema: RefinePromptInputSchema},
  output: {schema: RefinePromptOutputSchema},
  prompt: `You are an AI prompt expert. Your task is to refine a basic prompt idea into a more effective and detailed prompt based on the user's specifications.

Here's the basic prompt idea:
{{{promptIdea}}}

Desired style: {{{style}}}
Desired length: {{{length}}}
Desired tone: {{{tone}}}

Refined Prompt:`,
});

const refinePromptFlow = ai.defineFlow(
  {
    name: 'refinePromptFlow',
    inputSchema: RefinePromptInputSchema,
    outputSchema: RefinePromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
