// src/app/terms-and-conditions/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Home } from 'lucide-react'; // Icon for terms

export const metadata: Metadata = {
  title: 'Terms and Conditions - PromptForge',
  description: 'Terms and Conditions for using the PromptForge application.',
};

export default function TermsAndConditionsPage() {
  const appName = "PromptForge";
  // IMPORTANT: Replace with your actual company name and contact information
  const companyName = "Your Company Name"; 
  const contactEmail = "support@yourdomain.com";
  const effectiveDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div className="container mx-auto max-w-3xl py-8 px-4">
      <Card className="shadow-lg border-primary/20">
        <CardHeader className="text-center">
          <FileText className="mx-auto h-12 w-12 text-primary mb-3" />
          <CardTitle className="font-headline text-3xl md:text-4xl">Terms and Conditions</CardTitle>
          <CardDescription className="text-lg text-muted-foreground pt-1">
            Last Updated: {effectiveDate}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6 text-foreground">
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">1. Introduction</h2>
            <p>
              Welcome to {appName}! These Terms and Conditions (&quot;Terms&quot;) govern your use of the {appName} application (the &quot;Service&quot;), provided by {companyName} (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">2. Accounts</h2>
            <p>
              When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
            </p>
            <p>
              You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">3. Use of the Service</h2>
            <p>
              {appName} provides AI-powered prompt generation and refinement tools. You agree not to use the Service for any unlawful purpose or in any way that might harm, damage, or disparage any other party.
            </p>
            <p>
              You retain ownership of the content you create (e.g., prompt ideas). However, by using the Service, you grant us a license to use, process, and store this content as necessary to provide and improve the Service.
            </p>
            <p>
              The output generated by the AI models is for informational and creative purposes. We do not guarantee the accuracy, completeness, or suitability of any AI-generated content. You are responsible for reviewing and ensuring the appropriateness of any content before use.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">4. Intellectual Property</h2>
            <p>
              The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of {companyName} and its licensors.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">5. Termination</h2>
            <p>
              We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">6. Limitation of Liability</h2>
            <p>
              In no event shall {companyName}, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">7. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of Kolkata, West Bengal, India, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">8. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days&apos; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">9. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at: <Link href={`mailto:${contactEmail}`} className="text-accent hover:underline">{contactEmail}</Link>.
            </p>
          </section>
          
          <p className="text-sm text-muted-foreground text-center mt-8">
            <strong>Important:</strong> This is a template and should not be considered legal advice. Consult with a legal professional to ensure your Terms and Conditions are compliant and appropriate for your specific services.
          </p>
        </CardContent>
        <CardFooter className="flex justify-center pt-4">
          <Link href="/" passHref>
            <Button variant="outline">
              <Home className="mr-2 h-4 w-4" />
              Back to Home
            </Button>
          </Link>
        </CardFooter>
      </Card>
    </div>
  );
}

