
// src/app/terms-and-conditions/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Home } from 'lucide-react'; // Icon for terms

export const metadata: Metadata = {
  title: 'Terms and Conditions - PromptForge',
  description: 'Terms and Conditions for using the PromptForge application.',
};

export default function TermsAndConditionsPage() {
  const appName = "PromptForge";
  const companyName = "Lumen Labs"; 
  const contactEmail = "tirthankardasgupta913913@gmail.com";
  const effectiveDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div className="container mx-auto max-w-3xl py-8 px-4">
      <Card className="shadow-lg border-primary/20">
        <CardHeader className="text-center">
          <FileText className="mx-auto h-12 w-12 text-primary mb-3" />
          <CardTitle className="font-headline text-3xl md:text-4xl">Terms and Conditions</CardTitle>
          <CardDescription className="text-lg text-muted-foreground pt-1">
            Last Updated: {effectiveDate}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6 text-foreground">
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">1. Introduction</h2>
            <p>
              Welcome to {appName}! These Terms and Conditions (&quot;Terms&quot;) govern your use of the {appName} application (the &quot;Service&quot;), provided by {companyName}. By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">2. Accounts</h2>
            <p>
              When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
            </p>
            <p>
              You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.
            </p>
             <p>
              You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">3. Use of the Service</h2>
            <p>
              {appName} provides AI-powered prompt generation and refinement tools. You are granted a limited, non-exclusive, non-transferable, revocable license to use the Service for your personal, non-commercial use, or internal business purposes, subject to these Terms.
            </p>
            <p>
              You agree not to use the Service:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-1 mt-2">
                <li>For any unlawful purpose or in any way that might harm, damage, or disparage any other party.</li>
                <li>To generate content that is illegal, harmful, defamatory, obscene, infringing, harassing, or otherwise objectionable.</li>
                <li>To attempt to gain unauthorized access to the Service, other accounts, computer systems, or networks connected to the Service.</li>
                <li>To reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code or underlying ideas or algorithms of the Service.</li>
            </ul>
            <p className="mt-2">
              You retain ownership of the original content (e.g., prompt ideas) you submit to the Service (&quot;User Content&quot;). However, by submitting User Content, you grant us a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, process, reproduce, distribute, prepare derivative works of, display, and perform the User Content in connection with the Service and our (and our successors' and affiliates') business, including for promoting and redistributing part or all of the Service.
            </p>
            <p className="mt-2">
              The output generated by the AI models (&quot;Generated Content&quot;) is provided for informational and creative purposes. While you may use Generated Content for various purposes, we make no representations or warranties regarding its accuracy, completeness, suitability, or non-infringement of third-party rights. You are solely responsible for reviewing and ensuring the appropriateness and legality of any Generated Content before use, and for complying with any applicable AI model provider terms.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">4. Intellectual Property</h2>
            <p>
              The Service and its original content (excluding User Content and Generated Content, except as licensed to us), features, and functionality are and will remain the exclusive property of {companyName} and its licensors. The Service is protected by copyright, trademark, and other laws of both India and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of {companyName}.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">5. Termination</h2>
            <p>
              We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
            </p>
            <p>
              If you wish to terminate your account, you may simply discontinue using the Service or contact us to request account deletion. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">6. Disclaimer of Warranties</h2>
            <p>
             THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS. YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, {companyName} AND ITS AFFILIATES, LICENSORS, AND SUPPLIERS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">7. Limitation of Liability</h2>
            <p>
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL {companyName}, NOR ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (II) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (III) ANY CONTENT OBTAINED FROM THE SERVICE (INCLUDING GENERATED CONTENT); AND (IV) UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">8. Indemnification</h2>
            <p>
                You agree to defend, indemnify and hold harmless {companyName} and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney&apos;s fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; b) a breach of these Terms, or c) Content posted on the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">9. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of Kolkata, West Bengal, India, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">10. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days&apos; notice prior to any new terms taking effect by posting the new Terms on this site or by other means of communication. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-primary">11. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at: <Link href={`mailto:${contactEmail}`} className="text-accent hover:underline">{contactEmail}</Link>.
            </p>
          </section>
        </CardContent>
        <CardFooter className="flex justify-center pt-4">
          <Link href="/" passHref>
            <Button variant="outline">
              <Home className="mr-2 h-4 w-4" />
              Back to Home
            </Button>
          </Link>
        </CardFooter>
      </Card>
    </div>
  );
}

    